### ISSUE TITLE
Interfering internal CF addresses 

### ISSUE THREAD

**Issue by GwnDaan** [Open-Agriculture/AgIsoStack-plus-plus#192]
**Describe the bug**
When creating two internal CF addresses with the same preferred address, they will both continue using the same address. This causes information for one devices to be handled by both and leading to undefined behavior. This bug occurred by running two executables, though it might also happen within the same executable?

**How to replicate**
Run the VT "auxiliary function" and "version3 object pool" examples simultaneously, with both of them preferring the same internal address.

**Comment by ad3154** [comment]
I think the real issue here might be that your 2 executables have the same ISO NAMEs, which is not allowed, and we have no way to prevent across 2 executables. In theory, the stack should resolve them to different addresses even if they share the same preferred address if their ISO NAME is different. If you change one of the NAMEs and it still does this, then we'll have to take a closer look...

**Comment by GwnDaan** [comment]
Hmm I just tried to define unique NAMEs for them, it seems to solve half of the issue. With some specific combination of NAMEs they still acquire the same address. To reproduce:

First running the "aux input" and "aux functions" example together on [this branch](https://github.com/GwnDaan/ISO11783-CAN-Stack/tree/bug/claiming-same-address). It works fine and they both claim separate addresses.
![image](https://user-images.githubusercontent.com/29043784/221435096-dc96b693-38c0-4a95-90fd-36ece9ec75cd.png)
The difference between the NAMEs for them is:
```cpp
/// aux_inputs NAME: 
TestDeviceNAME.set_ecu_instance(1);
TestDeviceNAME.set_function_instance(0);

/// aux_functions NAME:
TestDeviceNAME.set_ecu_instance(0);
TestDeviceNAME.set_function_instance(1);
```

But when running "aux input"/"aux functions" together with "version3_object_pool", in both cases I get the same bug:
![image](https://user-images.githubusercontent.com/29043784/221435120-8d7056f6-6a16-49d1-a85e-0748193a77ff.png)
The difference of "version3_object_pool"  over the others is:
```cpp
TestDeviceNAME.set_ecu_instance(0);
TestDeviceNAME.set_function_instance(0);
```

Any idea what this cause of this might be? Or is this intentional for specific NAME combinations?

**Comment by ad3154** [comment]
Well, two control functions with different NAMEs should never collide, so there might be some issue there. I'll probably need to try and reproduce it to see what's going on. If possible, can you provide a `candump -l` trace of this?

**Comment by GwnDaan** [comment]
Sorry, it took a while before I had the VT back on my desk to test with again. Busy times on the farm already 💩. Let me know if you can find anything, I can't really make anything of it. 

[candump-2023-03-10_224131.log](https://github.com/ad3154/Isobus-plus-plus/files/10946355/candump-2023-03-10_224131.log)

The corresponding consoles (Note that I ran the right one (aux functions) before the left one (virtual terminal), the other way around they claim just fine):
![image](https://user-images.githubusercontent.com/29043784/224434328-c8537bde-5f12-4b20-b925-edd5c9d5c07c.png)

**Comment by GwnDaan** [comment]
Oh, here is the log of the other way around:
[candump-2023-03-10_224756.log](https://github.com/ad3154/Isobus-plus-plus/files/10946404/candump-2023-03-10_224756.log)

With the consoles:
![image](https://user-images.githubusercontent.com/29043784/224434991-e1f0ffec-13f0-40f7-83e3-2e336549f65b.png)

**Comment by ad3154** [comment]
Excellent, I will try and take a look at this over the weekend

**Comment by ad3154** [comment]
Ahhhhh I see. What you are seeing is this:
![image](https://user-images.githubusercontent.com/10929341/224516821-b321cca1-04ca-479f-a271-ea7facaeb5ef.png)

Basically, since they both have 0x1C as their preferred address, the one with the lower ISO NAME wins according to the standard. The aux input example moves to address 0x80 since it failed arbitrating for 0x1C. This is normal, as expected behavior as far as I know.

**Comment by ad3154** [comment]
I think we may want to add logging statements to the address claiming state machine to make this more clear, because in the logs it is tough to tell what is happening without the candump
