### ISSUE TITLE
SocketCAN utility function to parse available interfaces

### ISSUE THREAD

**Issue by GwnDaan** [Open-Agriculture/AgIsoStack-plus-plus#360]
The (static) function should be able to parse and list all available CAN interfaces on the system. This could be useful for applications that need to interact with multiple CAN devices, or for debugging purposes. The function should return a list of interface names, which can be used to open and configure the respective CAN interfaces.

**Comment by SumitkumarSatpute** [comment]
Hi there I would like help you with this issue, can you please explain bit more please ?
