### ISSUE TITLE
Add guaranteed delivery of changes for VT client  

### ISSUE THREAD

**Issue by GwnDaan** [Open-Agriculture/AgIsoStack-plus-plus#362]
As discussed in https://github.com/Open-Agriculture/AgIsoStack-plus-plus/issues/231, "some calls to send_something in the VT client fail sometimes". This essentially means that it is **not** guaranteed that sent changes actually arrive at the VT server. 

Since most applications will want their changes to be reliable delivered to the VT server, we can (try to) provide an interface for ensuring delivery.

I think a good starting point is to ensure that the message is actually sent on the bus to the VT, but ultimately we should also check the responses from the VT where possible.

**Comment by ad3154** [comment]
Yep, I think that's a good approach - we may also want to have some way to disable/bypass it as well which could be nice on platforms with less RAM.
