### ISSUE TITLE
advanced-example / SeederExample e -  only 1 of 6 sections is controlles by TC-Client

### ISSUE THREAD

**Issue by engel2** [Open-Agriculture/AgIsoStack-plus-plus#428]
**Describe the bug**
The SeederExample shows six supported sections in the task controller. But there is only one section switched. The TaskControllerClientExample works fine with 16 sections and the same hardware setup (same TC-Server).

**Supporting Documentation**
[SeederExample-OneSectionOnly.log](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/files/14164389/SeederExample-OneSectionOnly.log)

**Environment (please complete the following information):**

- OS: Win10
- Compiler GCC 12.2.0
- CAN Driver PCAN-USB
- Müller Touch 1200 with ISOBUS-TC
- NMEA0183 Simulator

**Additional context**
Add any other context about the problem here that you think might help us recreate or otherwise address your issue if applicable.

https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/50421355/544957d6-9d58-435c-a9d7-9301daf779e2

![TCClientExample](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/50421355/415a4a76-e7d8-481e-9791-ae4ba9d1a20f)

**Comment by GwnDaan** [comment]
Hi there, which branch are you testing the seeder-example on? Could you try the "daan/advanced-example" branch and see if that's any better?

**Comment by engel2** [comment]
I tested it with this branch and I think that I identified the bug.
The break command is on the wrong position. 
I put it in the else statement and all sections are working. Don't know if this is well coded, but it works so far.  Maybe you can check it.
My fixed version:
![SeederExample_fixed](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/50421355/3762b931-8b50-43df-b608-cba56cae59fd)

version from "daan/advanced-example":
![SeederExample_bug](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/50421355/990a8c44-d0a2-4144-bab3-07bff945d454)
