### ISSUE TITLE
Error occurred in seeder_example

### ISSUE THREAD

**Issue by JayQu9** [Open-Agriculture/AgIsoStack-plus-plus#449]
**Describe the bug**

After loading the object pool, a quick click on the settings button gives me an error
[Info][VT]: Loaded object pool version from VT non-volatile memory with no errors.
[Warn][VT]: Server response to a command timed out
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 18446744073674967472)

Sometimes, an error occurs after the Server response to a command timed out

[Warn][VT]: Server response to a command timed out
terminate called after throwing an instance of 'std::out_of_range'
  what():  vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)

**Environment (please complete the following information):**
- OS: win10
- Compiler GCC 7.3.0
- CAN Driver PCAN

**Comment by GwnDaan** [comment]
Hi there, thanks for reporting this issue.

Since there is no trace in the error message currently, it is hard for us to find the exact location. Can you run a debug session so it stops at the point where the exception occurs, and provide us with the stack trace?

**Comment by JayQu9** [comment]
After clicking debug, continue to click the setting soft key immediately before the object pool is loaded, it will exit directly.
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/46147928/96f9a267-ec7c-4a9d-89a6-607d8faf545b)
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/46147928/c668b6cd-bc0d-4a87-95a5-2c6eb40452a1)

**Comment by JayQu9** [comment]
After clicking debug, continue to click the setting soft key immediately before the object pool is loaded, it will exit directly.
![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/46147928/35cfbe78-6550-47c8-9185-e8bc6c785e31)

![image](https://github.com/Open-Agriculture/AgIsoStack-plus-plus/assets/46147928/cd098804-6c42-4c22-a45b-2f546c136bff)
