### ISSUE TITLE
Machine Direction wrong enum vaues

### ISSUE THREAD

**Issue by Strambauer** [Open-Agriculture/AgIsoStack-plus-plus#491]
**Describe the bug**
The enum MachineDirection in file "isobus_speed_distance_messages.hpp" has wrong values for forwad and reverse.

**Supporting Documentation**
The Enum says Forward = 0 and Reverse = 1 (isobus_speed_distance_messages.hpp line 49) , the standard says reverse = 0 and forward = 1 (ISO 11783-7 A.10)

**Comment by ad3154** [comment]
Yeah SPN 1861, 4309, 1864, and 4312 are all reverse = 0.

Not sure how that got flipped in the enum. Will update it.
