### ISSUE TITLE
VT Capabilities Callback?

### ISSUE THREAD

**Issue by ad3154** [Open-Agriculture/AgIsoStack-plus-plus#515]
**Is your feature request related to a problem? Please describe.**
There's no great way to dynamically chose specific set of object pools based on the content of various server messages, like number of soft keys, or data mask size.

**Describe the solution you'd like**
It would be nice to have a callback or something to allow the user to select the correct object pool at connection time.

**Comment by GwnDaan** [comment]
Duplicate of #376 ?

**Comment by ad3154** [comment]
Yeah I suppose it is a duplicate.
